### ISSUE TITLE
Please cut a new release to pick up LICENSE file

### ISSUE THREAD

**Issue by polds** [go-chi/stampede#5]
Related to #4, It looks like pkg.go.dev serves a cached version of the latest _tagged release_ which in this case is v0.4.4 and does not include the LICENSE file. 

So if you visit https://pkg.go.dev/github.com/go-chi/stampede it tries to serve the docs for v0.4.4. You can coerce it to fetch a new version from master which correctly indexes everything (https://pkg.go.dev/github.com/go-chi/stampede/@master), but this is not the default serving tag.

Releasing a v0.4.5 which includes the LICENSE file should fix it.

**Comment by pkieltyka** [comment]
here ya go https://github.com/go-chi/stampede/tree/v0.4.5 :pray:
